# Generated by Django 2.1.1 on 2018-09-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_customizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstraptheme',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitebootstraptheme',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
